packages:
  - apps/*
injectWorkspacePackages: true
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - esbuild
  - prisma
  - unrs-resolver
syncInjectedDepsAfterScripts:
  - build
