packages:
  - apps/*
  - packages/*
injectWorkspacePackages: true
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/engines'
  - '@swc/core'
  - esbuild
  - prisma
syncInjectedDepsAfterScripts:
  - build